executable              = execute_reversibility_to_REI.sh

output                  = ../log/out/r_to_LEI.$(ClusterId).$(ProcId).out
error                   = ../log/err/r_to_LEI.$(ClusterId).$(ProcId).err
log                     = ../log/log/r_to_LEI.$(ClusterId).log

should_transfer_files   = YES

transfer_input_files    = ./reversibility_to_REI.py, ./execute_reversibility_to_REI.py

when_to_transfer_output = ON_EXIT

+JobFlavour = "workday"

request_CPUs = 1

queue