executable              = execute_displacement_to_LEI.sh

output                  = ../log/out/d_to_LEI.$(ClusterId).$(ProcId).out
error                   = ../log/err/d_to_LEI.$(ClusterId).$(ProcId).err
log                     = ../log/log/d_to_LEI.$(ClusterId).log

should_transfer_files   = YES

transfer_input_files    = ./displacement_to_LEI.py, ./execute_displacement_to_LEI.py

when_to_transfer_output = ON_EXIT

+JobFlavour = "testmatch"

request_CPUs = 1

queue
